apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "awspim.fullname" . }}
  labels:
    {{- include "awspim.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ include "awspim.configSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
